language: python
python:
  - "3.6"
#env:
#  global:
    # yaml build with a lot of warnings, which clutter the output
#    - PYTHONWARNINGS=ignore::yaml.YAMLLoadWarning
install:
  - pip install -e .
  - pip install pytest
  - pip install pytest-cov codecov coveralls  # install packages for code coverage report
script:
  - coverage run --source=pyactcv setup.py pytest
after_success:
  - coveralls # uploads report to codecov.io
