language: python
python:
  - "3.6"
install:
  - pip install -e .
  - pip install pytest
  #- pip install pytest-cov codecov  # install packages for code coverage report
script:
  - python setup.py pytest
#after_success:
#  - codecov                         # uploads report to codecov.io
